name: Run ElastAlert2

on:
  push:
    branches: [ dev ]
    paths:
      - 'elastalert/**'
      - '.github/workflows/elastalert.yml'

jobs:
  elastalert:
    runs-on: ubuntu-latest

    env:
      ELASTIC_HOST: ${{ secrets.ELASTIC_HOST }}
      ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name:  Install ElastAlert2
        run: |
          pip install elastalert2

      - name:  Generate smtp_auth.yaml from GitHub Secret
        run: |
          echo "user: hanchiangzo@gmail.com" > elastalert/smtp_auth.yaml
          echo "password: $EMAIL_APP_PASSWORD" >> elastalert/smtp_auth.yaml

      - name: üîç Verify Elasticsearch connection
        run: |
          echo "üîç ELASTIC_HOST: $ELASTIC_HOST"
          echo "üîç Testing Elasticsearch connection..."
          curl -X GET "$ELASTIC_HOST/_cluster/health" \
            -H "Authorization: ApiKey $ELASTIC_API_KEY" \
            -H 'Content-Type: application/json' \
            --fail --silent --show-error
          echo "‚úÖ Connection OK!"

          
      - name: Test ElastAlert rule (simulate historical log)
        run: |
          cd elastalert
          # ƒêi·ªÅu ch·ªânh --start v√† --end ƒë·ªÉ test rule tr√™n m·ªôt kho·∫£ng th·ªùi gian c·ª• th·ªÉ (v√≠ d·ª•: 10 ng√†y tr∆∞·ªõc)
          elastalert-test-rule --config config.yaml --start "2025-03-27T09:30:00" --end "2025-03-27T09:45:00" rules/t1059_python_exec.yaml

      - name:  Run ElastAlert2
        run: |
          cd elastalert
          elastalert --config config.yaml --verbose --start "2025-03-27T09:30:00" --end "2025-03-27T09:45:00"

